version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - 5431:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
